### PR TITLE
Moved configuration to json file

### PR DESCRIPTION
**Pull request by FelipeJz**
Always good the keep the config outside the code

### CODE REVIEW

**Comment by ben9583** [comment]
Thank you for making this! Maybe can you change it so that if `config.json` doesn't exist, it creates it with the defaults you have here?

**Comment by FelipeJz** [comment]
I'm happy to contribute to this project, been using it every day. 
The file is already created in the commit with the defaults, should we check anyway?

**Comment by ben9583** [comment]
I think so; that way if someone moves the python script elsewhere and they no longer have the config, they won't have to try and figure out the schema of the config

**Comment by ben9583** [comment]
Right now I'm working on an audio device selector so there will be some merge conflicts with this branch; I can help resolve some of those however

**Comment by ben9583** [comment]
I haven't tested these changes yet (just did it in the GitHub merge conflict resolver) so I'm gonna do that

**Comment by ben9583** [comment]
I think this should be good; basically what I did was I removed the constants and referenced all config values in the `config` object, that way any changes to `config` done by `update_config` will be propagated to the `config.json` and there shouldn't be any desync

**Comment by ben9583** [comment]
Ok so I merged this, thanks for contributing!

**Pull request merged**
