### PR TITLE
Audio input device select menu

### PR DESCRIPTION
**Pull request by GDNacho**
Added simple terminal to select which microphone to use
The script currently automatically selects 1 out of the audio devices array, which may cause an index error if there's less than 2 audio devices connected to your PC

### CODE REVIEW

**Comment by ben9583** [comment]
This is helpful, but ideally audio device selection would be part of the GUI and would save between sessions. I'll look into this though

**Comment by GDNacho** [comment]
> This is helpful, but ideally audio device selection would be part of the GUI and would save between sessions. I'll look into this though

I know, it's just something i did quickly to avoid an index out of bounds error

**Comment by ben9583** [comment]
Yea this actually helped me figure out why things weren't working when I first ran this; I'm doing the GUI thing now though

**Comment by ben9583** [comment]
Ok since the audio device selector is done I'm gonna close this now

**Pull request closed without merging**
